#!/bin/sh
### BEGIN INIT INFO
# Provides:             beavers-nanny
# Required-Start:       $all
# Required-Stop:        $all
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Beavers Nanny Server
### END INIT INFO

#export PATH=$PATH:/opt/node/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules
export HOME=/usr/share/beavers-nanny

case "$1" in
  start)
    /usr/local/bin/forever start -a -p /usr/share/beavers-nanny/.forever -o /usr/share/beavers-nanny/log/stdout -e /usr/share/beavers-nanny/log/stderr -l /usr/share/beavers-nanny/log/forever.log --workingDir=/usr/share/beavers-nanny /usr/share/beavers-nanny/server.js
    ;;
  stop)
    exec /usr/local/bin/forever stopall
    ;;
  *)

  echo "Usage: /etc/init.d/beavers-nanny {start|stop}"
  exit 1
  ;;
esac
exit 0
